[platformio]
extra_configs = ../../platformio/common.ini
default_envs = lolin_s2_mini
src_dir = .

[env:lolin_s2_mini]
extends = env:base_s2
lib_deps =
    ${env:base_s2.lib_deps}
    madhephaestus/ESP32Servo
